# Generated by Django 3.1.7 on 2021-04-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todotem',
            new_name='TodoItem',
        ),
    ]
